[package]
name = "kyc_registry"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "21.6.0" }

[dev-dependencies]
soroban-sdk = { version = "21.6.0", features = ["testutils"] }
